runtime: nodejs18

instance_class: F1

env_variables:
  NODE_ENV: production
  TELEGRAM_BOT_TOKEN: '6282164100:AAGiW-u88ZkIyOUHePs4z-R_t80qvUMfRWo'
  GC_BUCKET_PUBLIC: 'https://storage.googleapis.com/tbot_storage'
